### ISSUE TITLE
Allow only positive numbers

### ISSUE THREAD

**Issue by elieobeid7** [uhlryk/angular-dynamic-number#27] opened 2016-07-28 12:52 UTC
How to allow only positive numbers? I'm using angular 1.x and there's seem to be a bug or please show a working example. Users shouldn't be able to enter negative numbers.

**Comment by uhlryk** [comment] 2016-07-29 16:10
Please write how your directive looks like (what options you set). 
And additional info which are necessary to reproduce bug.

**Comment by elieobeid7** [comment] 2016-07-31 11:04
@uhlryk 

By modifying the "Number may be only negative, decimal separator dot" example to only accept positive number (so rename num-pos attribute to num-neg), you will see that the input behaves incorrectly whenever you type the negative sign first:

• It allows the sign symbol (-) to be typed (it has to be the first character typed)
• Then if you type a a digit, it deletes the sign symbol however it converts it to 0 and loose the digit you typed
• If you continue to type a second digit it is correctly taken into account
• If you only type in the sign symbol (-) the model is set to 0
• The behavior is correct if you don't type the sign symbol as the very first character

save this .html file and see, i cant share it here

http://pastebin.com/zTTCB33u

**Comment by uhlryk** [comment] 2016-07-31 13:38
thank you very much for your feedback. Yes it is bug. It should be fixed now. Please check if now it is better

**Comment by uhlryk** [comment] 2016-07-31 13:39
It is also in examples (8th input)

**Comment by elieobeid7** [comment] 2016-07-31 13:55
will check on monday and let you know, tuesday max. thank you!

**Comment by elieobeid7** [comment] 2016-08-02 17:57
Issue solved, you may close the ticket, thanks for your help

**Closed as completed** 2016-08-02 20:14 UTC
