### ISSUE TITLE
"undefined" appears in input box

### ISSUE THREAD

**Issue by TakahiRoyte** [uhlryk/angular-dynamic-number#3] opened 2016-01-14 01:11 UTC
currently I am binding the ng-model value to scope and this leads to a certain bug.  At the first time page loads, focus in input box and type any alphabets, it returns "undefined" in input box.  And this "undefined" does not get deleted unless you select all and press delete.  I tried to add some regexp replace to fix this but could not make it work...

is this causing because of the way I wrote the code?

http://plnkr.co/edit/692gy5

thank you for the directive, i really love the way it works.

**Comment by uhlryk** [comment] 2016-01-14 08:17
Hello,
thanks for your feedback. I can reproduce this bug.I will fix it today after work.

**Comment by uhlryk** [comment] 2016-01-14 19:05
You have error because your model init value is undefined. In examples I set model init value by form attribute `ng-init="value1 = ''"` In your example your model is `testValue` but you set init values for models from my example instead of your model.
I update your example : http://plnkr.co/edit/tWCbwQsnHVQUwTyMYArp?p=preview please try it. Look at form tag and ng-init directive for see changes.

Thanks to you, I decided to check if model value is undefined. And if yes then directive return empty string.

Please try it, and if everything is correct now, then close this task. If something is still wrong, please describe it.

Thanks for your contribution

**Comment by TakahiRoyte** [comment] 2016-01-15 00:41
Thanks for the example, now I see what I was doing and how the directive was supposed to be used.  And also, I tried the updated directive and it works perfect.  Just as I intended.

Great thanks to you and your rapid response.

**Closed as completed** 2016-01-17 18:48 UTC

**Comment by TakahiRoyte** [comment] 2016-01-19 07:36
Hello again, let me ask you one more favor.Is it possible to update the source on bower?
when I type `bower info angular-dynamic-number`, it still shows me 1.5.0 version of your work.

I don't know how you registered it, but the command below may work. Please check.

``` bash
git tag -a v1.5.3 -m "Release version 1.5.3"
git push origin master --tags 
```

Thanks.

**Comment by uhlryk** [comment] 2016-01-19 20:19
@TakahiRoyte thank you very much for your watchfulness. Yes I forgot, that bower for update need tags (I added them only for minor and major changes). I was focus on npm.
I added new tag (1.5.4 because I spot some typo in package.json).

**Comment by TakahiRoyte** [comment] 2016-01-22 07:09
@uhlryk thank you for the fix! Greatly appreciated.
